services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    volumes:
      - redis:/data

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    image: 'rhossain16/nginx:latest'
    ports:
      - '80:80'

  api:
    build:
      context: ./server
    image: 'rhossain16/server:latest'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  client:
    build:
      context: ./client
    image: 'rhossain16/client:latest'
    environment:
      - WDS_SOCKET_PORT=0

  worker:
    build:
      context: ./worker
    image: 'rhossain16/worker:latest'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

volumes:
  postgres:
  redis:
